name: Trigger auto deployment for aca-bolao-api-v1 # NÃO MUDAR

on:
  push:
    branches:
      - master # Garante que só roda quando o master é atualizado
    paths:
      - 'Dockerfile'
      - 'src/**'
  workflow_dispatch:

env:
  AZURE_CONTAINER_APPS_RESOURCE_GROUP: rg-banco-itens-dev # MANTENHA O SEU NOME DE RG
  AZURE_CONTAINER_APPS_NAME: aca-bolao-api-v1 # MANTENHA O SEU NOME DO ACA
  AZURE_CONTAINER_APPS_ENVIRONMENT: env-bancodeitens # MANTENHA O SEU NOME DO AMBIENTE
  CONTAINER_REGISTRY_NAME: acrbancoitensdev # MANTENHA SEU NOME DO ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_CREDENTIALS }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          acrName: ${{ env.CONTAINER_REGISTRY_NAME }}
          containerAppName: ${{ env.AZURE_CONTAINER_APPS_NAME }}
          resourceGroup: ${{ env.AZURE_CONTAINER_APPS_RESOURCE_GROUP }}
          containerAppEnvironment: ${{ env.AZURE_CONTAINER_APPS_ENVIRONMENT }}
          imageToBuild: ${{ env.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ env.AZURE_CONTAINER_APPS_NAME }}:${{ github.sha }}
          dockerfilePath: Dockerfile
          
          # ====================================================
          # CRÍTICO: ADICIONA O PARÂMETRO SEM CACHE
          # Isso deve resolver o problema de o Npgsql estar 'preso'
          # ====================================================
          buildArguments: '--no-cache'
          
          targetPort: 8080
          ingress: external
